# Stage 1: Compile and Build angular codebase
# Use official node image as the base image
FROM node:20.18.3-alpine as build

# Set the working directory
WORKDIR /usr/local/app

COPY package*.json .
COPY *.tgz ./  

# Install all the dependencies
RUN npm install --legacy-peer-deps

COPY . .

# Generate the build of the application
RUN npm run dev


# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/local/app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80