apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "selectorLabels" . | nindent 4 }}